POST   http://localhost:3000/api/auth/signUp
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNzM5MjA0NzM3fQ.gnwojxWbtj7Q0NCAtmpobA-3ncsA9dow1hNIXaqmxGE

{
    "name" : "salah",
    "password" : "m",
    "type" : "RH",
    "email" : "boukairsalah@gmail.com"
}