GET http://localhost:3000/api/RH/addRoom
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvdWthaXJzYWxhaEBnbWFpbC5jb20iLCJpYXQiOjE3MzgzNjg0MTEsImV4cCI6MTczODM3MjAxMX0.Ejgb4zU_6LO-gnityMCZ5aQavKhIKAXnkt0QhMdH1GA
